### ISSUE TITLE
Missing USGS_LPC_MA_NE_CMGP_Snds_2013_LAS_2015/ept.json

### ISSUE THREAD

**Issue by rmilbert** [hobuinc/usgs-lidar#78] opened 2024-10-31 19:36 UTC
The lidar catalog (https://usgs-lidar-stac.s3-us-west-2.amazonaws.com/ept/catalog.json) references a feature (https://s3-us-west-2.amazonaws.com/usgs-lidar-stac/ept/USGS_LPC_MA_NE_CMGP_Snds_2013_LAS_2015.json) which references a tile (https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_MA_NE_CMGP_Snds_2013_LAS_2015/ept.json) that is missing.

Any chance you could fix it?

Thanks so much for hosting this useful resource!

**Comment by hobu** [comment] 2024-11-01 15:02
It was a duplicate of `USGS_LPC_MA_NE_CMGP_Sandy_Z18_2013` and was removed. The catalog should be refreshed during the next cycle to remove it (2-3 days IIRC). Please reopen if this is still an issue

**Closed as completed by hobu** 2024-11-01 15:02 UTC
